ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.2
    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    imu0: /imu/data
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  false, false, true]
    imu0_differential: false
    imu0_relative: true
    imu0_remove_gravitational_acceleration: true

    use_control: false
    stamped_control: false
    print_diagnostics: true
    debug: false